//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BokenDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoekenDatabaseEntities : DbContext
    {
        public BoekenDatabaseEntities()
            : base("name=BoekenDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteur> Auteurs { get; set; }
        public virtual DbSet<BoekenAuteur> BoekenAuteurs { get; set; }
        public virtual DbSet<BoekenGenre> BoekenGenres { get; set; }
        public virtual DbSet<Boek> Boeks { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Uitgeverijen> Uitgeverijens { get; set; }
    }
}
